#!/usr/bin/env bash

#MOVE IN THE DIRECTORY CONTAINING THE BLISS SCRIPT 
# cd ../bin

#CREATE THE PATTERN FILE: TEST_DMSO_AGCCATCA 
bash "$BLISS_PATH"/prepare_pattern.sh samplesheet/test.csv

# #MOVE THE PATTERN FILE IN THE PROPER DIRECTORY
# mv TEST_DMSO_AGCCATCA ../patterns

#CREATE THE SCRIPT TO RUN BLISS
bash "$BLISS_PATH"/prepare_run.sh samplesheet/test.csv TEST fastq

#EXECUTE THE RUN FILE
bash ./runs/run_pipeline_TEST.sh

#GO BACK TO ORIGINAL DIRECTORY
# cd ../test

